version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

#  postgres:
#    image: postgres:12.0-alpine
#    restart: always
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
#      - POSTGRES_DB=app
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=pass

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'