version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./datams:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'